/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package mil.nga.giat.geowave.adapter.vector.simpleFeature.avro;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class FeatureDefinition extends
		org.apache.avro.specific.SpecificRecordBase implements
		org.apache.avro.specific.SpecificRecord
{
	public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"FeatureDefinition\",\"namespace\":\"mil.nga.giat.geowave.adapter.vector.simpleFeature.avro\",\"fields\":[{\"name\":\"FeatureTypeName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"AttributeNames\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}},{\"name\":\"AttributeTypes\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}},{\"name\":\"AttributeDefaultClassifications\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}}]}");

	public static org.apache.avro.Schema getClassSchema() {
		return SCHEMA$;
	}

	@Deprecated
	public java.lang.String FeatureTypeName;
	@Deprecated
	public java.util.List<java.lang.String> AttributeNames;
	@Deprecated
	public java.util.List<java.lang.String> AttributeTypes;
	@Deprecated
	public java.util.List<java.lang.String> AttributeDefaultClassifications;

	/**
	 * Default constructor. Note that this does not initialize fields to their
	 * default values from the schema. If that is desired then one should use
	 * <code>newBuilder()</code>.
	 */
	public FeatureDefinition() {}

	/**
	 * All-args constructor.
	 */
	public FeatureDefinition(
			java.lang.String FeatureTypeName,
			java.util.List<java.lang.String> AttributeNames,
			java.util.List<java.lang.String> AttributeTypes,
			java.util.List<java.lang.String> AttributeDefaultClassifications ) {
		this.FeatureTypeName = FeatureTypeName;
		this.AttributeNames = AttributeNames;
		this.AttributeTypes = AttributeTypes;
		this.AttributeDefaultClassifications = AttributeDefaultClassifications;
	}

	public org.apache.avro.Schema getSchema() {
		return SCHEMA$;
	}

	// Used by DatumWriter. Applications should not call.
	public java.lang.Object get(
			int field$ ) {
		switch (field$) {
			case 0:
				return FeatureTypeName;
			case 1:
				return AttributeNames;
			case 2:
				return AttributeTypes;
			case 3:
				return AttributeDefaultClassifications;
			default:
				throw new org.apache.avro.AvroRuntimeException(
						"Bad index");
		}
	}

	// Used by DatumReader. Applications should not call.
	@SuppressWarnings(value = "unchecked")
	public void put(
			int field$,
			java.lang.Object value$ ) {
		switch (field$) {
			case 0:
				FeatureTypeName = (java.lang.String) value$;
				break;
			case 1:
				AttributeNames = (java.util.List<java.lang.String>) value$;
				break;
			case 2:
				AttributeTypes = (java.util.List<java.lang.String>) value$;
				break;
			case 3:
				AttributeDefaultClassifications = (java.util.List<java.lang.String>) value$;
				break;
			default:
				throw new org.apache.avro.AvroRuntimeException(
						"Bad index");
		}
	}

	/**
	 * Gets the value of the 'FeatureTypeName' field.
	 */
	public java.lang.String getFeatureTypeName() {
		return FeatureTypeName;
	}

	/**
	 * Sets the value of the 'FeatureTypeName' field.
	 * 
	 * @param value
	 *            the value to set.
	 */
	public void setFeatureTypeName(
			java.lang.String value ) {
		this.FeatureTypeName = value;
	}

	/**
	 * Gets the value of the 'AttributeNames' field.
	 */
	public java.util.List<java.lang.String> getAttributeNames() {
		return AttributeNames;
	}

	/**
	 * Sets the value of the 'AttributeNames' field.
	 * 
	 * @param value
	 *            the value to set.
	 */
	public void setAttributeNames(
			java.util.List<java.lang.String> value ) {
		this.AttributeNames = value;
	}

	/**
	 * Gets the value of the 'AttributeTypes' field.
	 */
	public java.util.List<java.lang.String> getAttributeTypes() {
		return AttributeTypes;
	}

	/**
	 * Sets the value of the 'AttributeTypes' field.
	 * 
	 * @param value
	 *            the value to set.
	 */
	public void setAttributeTypes(
			java.util.List<java.lang.String> value ) {
		this.AttributeTypes = value;
	}

	/**
	 * Gets the value of the 'AttributeDefaultClassifications' field.
	 */
	public java.util.List<java.lang.String> getAttributeDefaultClassifications() {
		return AttributeDefaultClassifications;
	}

	/**
	 * Sets the value of the 'AttributeDefaultClassifications' field.
	 * 
	 * @param value
	 *            the value to set.
	 */
	public void setAttributeDefaultClassifications(
			java.util.List<java.lang.String> value ) {
		this.AttributeDefaultClassifications = value;
	}

	/** Creates a new FeatureDefinition RecordBuilder */
	public static mil.nga.giat.geowave.adapter.vector.simpleFeature.avro.FeatureDefinition.Builder newBuilder() {
		return new mil.nga.giat.geowave.adapter.vector.simpleFeature.avro.FeatureDefinition.Builder();
	}

	/**
	 * Creates a new FeatureDefinition RecordBuilder by copying an existing
	 * Builder
	 */
	public static mil.nga.giat.geowave.adapter.vector.simpleFeature.avro.FeatureDefinition.Builder newBuilder(
			mil.nga.giat.geowave.adapter.vector.simpleFeature.avro.FeatureDefinition.Builder other ) {
		return new mil.nga.giat.geowave.adapter.vector.simpleFeature.avro.FeatureDefinition.Builder(
				other);
	}

	/**
	 * Creates a new FeatureDefinition RecordBuilder by copying an existing
	 * FeatureDefinition instance
	 */
	public static mil.nga.giat.geowave.adapter.vector.simpleFeature.avro.FeatureDefinition.Builder newBuilder(
			mil.nga.giat.geowave.adapter.vector.simpleFeature.avro.FeatureDefinition other ) {
		return new mil.nga.giat.geowave.adapter.vector.simpleFeature.avro.FeatureDefinition.Builder(
				other);
	}

	/**
	 * RecordBuilder for FeatureDefinition instances.
	 */
	public static class Builder extends
			org.apache.avro.specific.SpecificRecordBuilderBase<FeatureDefinition> implements
			org.apache.avro.data.RecordBuilder<FeatureDefinition>
	{

		private java.lang.String FeatureTypeName;
		private java.util.List<java.lang.String> AttributeNames;
		private java.util.List<java.lang.String> AttributeTypes;
		private java.util.List<java.lang.String> AttributeDefaultClassifications;

		/** Creates a new Builder */
		private Builder() {
			super(
					mil.nga.giat.geowave.adapter.vector.simpleFeature.avro.FeatureDefinition.SCHEMA$);
		}

		/** Creates a Builder by copying an existing Builder */
		private Builder(
				mil.nga.giat.geowave.adapter.vector.simpleFeature.avro.FeatureDefinition.Builder other ) {
			super(
					other);
			if (isValidValue(
					fields()[0],
					other.FeatureTypeName)) {
				this.FeatureTypeName = data().deepCopy(
						fields()[0].schema(),
						other.FeatureTypeName);
				fieldSetFlags()[0] = true;
			}
			if (isValidValue(
					fields()[1],
					other.AttributeNames)) {
				this.AttributeNames = data().deepCopy(
						fields()[1].schema(),
						other.AttributeNames);
				fieldSetFlags()[1] = true;
			}
			if (isValidValue(
					fields()[2],
					other.AttributeTypes)) {
				this.AttributeTypes = data().deepCopy(
						fields()[2].schema(),
						other.AttributeTypes);
				fieldSetFlags()[2] = true;
			}
			if (isValidValue(
					fields()[3],
					other.AttributeDefaultClassifications)) {
				this.AttributeDefaultClassifications = data().deepCopy(
						fields()[3].schema(),
						other.AttributeDefaultClassifications);
				fieldSetFlags()[3] = true;
			}
		}

		/** Creates a Builder by copying an existing FeatureDefinition instance */
		private Builder(
				mil.nga.giat.geowave.adapter.vector.simpleFeature.avro.FeatureDefinition other ) {
			super(
					mil.nga.giat.geowave.adapter.vector.simpleFeature.avro.FeatureDefinition.SCHEMA$);
			if (isValidValue(
					fields()[0],
					other.FeatureTypeName)) {
				this.FeatureTypeName = data().deepCopy(
						fields()[0].schema(),
						other.FeatureTypeName);
				fieldSetFlags()[0] = true;
			}
			if (isValidValue(
					fields()[1],
					other.AttributeNames)) {
				this.AttributeNames = data().deepCopy(
						fields()[1].schema(),
						other.AttributeNames);
				fieldSetFlags()[1] = true;
			}
			if (isValidValue(
					fields()[2],
					other.AttributeTypes)) {
				this.AttributeTypes = data().deepCopy(
						fields()[2].schema(),
						other.AttributeTypes);
				fieldSetFlags()[2] = true;
			}
			if (isValidValue(
					fields()[3],
					other.AttributeDefaultClassifications)) {
				this.AttributeDefaultClassifications = data().deepCopy(
						fields()[3].schema(),
						other.AttributeDefaultClassifications);
				fieldSetFlags()[3] = true;
			}
		}

		/** Gets the value of the 'FeatureTypeName' field */
		public java.lang.String getFeatureTypeName() {
			return FeatureTypeName;
		}

		/** Sets the value of the 'FeatureTypeName' field */
		public mil.nga.giat.geowave.adapter.vector.simpleFeature.avro.FeatureDefinition.Builder setFeatureTypeName(
				java.lang.String value ) {
			validate(
					fields()[0],
					value);
			this.FeatureTypeName = value;
			fieldSetFlags()[0] = true;
			return this;
		}

		/** Checks whether the 'FeatureTypeName' field has been set */
		public boolean hasFeatureTypeName() {
			return fieldSetFlags()[0];
		}

		/** Clears the value of the 'FeatureTypeName' field */
		public mil.nga.giat.geowave.adapter.vector.simpleFeature.avro.FeatureDefinition.Builder clearFeatureTypeName() {
			FeatureTypeName = null;
			fieldSetFlags()[0] = false;
			return this;
		}

		/** Gets the value of the 'AttributeNames' field */
		public java.util.List<java.lang.String> getAttributeNames() {
			return AttributeNames;
		}

		/** Sets the value of the 'AttributeNames' field */
		public mil.nga.giat.geowave.adapter.vector.simpleFeature.avro.FeatureDefinition.Builder setAttributeNames(
				java.util.List<java.lang.String> value ) {
			validate(
					fields()[1],
					value);
			this.AttributeNames = value;
			fieldSetFlags()[1] = true;
			return this;
		}

		/** Checks whether the 'AttributeNames' field has been set */
		public boolean hasAttributeNames() {
			return fieldSetFlags()[1];
		}

		/** Clears the value of the 'AttributeNames' field */
		public mil.nga.giat.geowave.adapter.vector.simpleFeature.avro.FeatureDefinition.Builder clearAttributeNames() {
			AttributeNames = null;
			fieldSetFlags()[1] = false;
			return this;
		}

		/** Gets the value of the 'AttributeTypes' field */
		public java.util.List<java.lang.String> getAttributeTypes() {
			return AttributeTypes;
		}

		/** Sets the value of the 'AttributeTypes' field */
		public mil.nga.giat.geowave.adapter.vector.simpleFeature.avro.FeatureDefinition.Builder setAttributeTypes(
				java.util.List<java.lang.String> value ) {
			validate(
					fields()[2],
					value);
			this.AttributeTypes = value;
			fieldSetFlags()[2] = true;
			return this;
		}

		/** Checks whether the 'AttributeTypes' field has been set */
		public boolean hasAttributeTypes() {
			return fieldSetFlags()[2];
		}

		/** Clears the value of the 'AttributeTypes' field */
		public mil.nga.giat.geowave.adapter.vector.simpleFeature.avro.FeatureDefinition.Builder clearAttributeTypes() {
			AttributeTypes = null;
			fieldSetFlags()[2] = false;
			return this;
		}

		/** Gets the value of the 'AttributeDefaultClassifications' field */
		public java.util.List<java.lang.String> getAttributeDefaultClassifications() {
			return AttributeDefaultClassifications;
		}

		/** Sets the value of the 'AttributeDefaultClassifications' field */
		public mil.nga.giat.geowave.adapter.vector.simpleFeature.avro.FeatureDefinition.Builder setAttributeDefaultClassifications(
				java.util.List<java.lang.String> value ) {
			validate(
					fields()[3],
					value);
			this.AttributeDefaultClassifications = value;
			fieldSetFlags()[3] = true;
			return this;
		}

		/**
		 * Checks whether the 'AttributeDefaultClassifications' field has been
		 * set
		 */
		public boolean hasAttributeDefaultClassifications() {
			return fieldSetFlags()[3];
		}

		/** Clears the value of the 'AttributeDefaultClassifications' field */
		public mil.nga.giat.geowave.adapter.vector.simpleFeature.avro.FeatureDefinition.Builder clearAttributeDefaultClassifications() {
			AttributeDefaultClassifications = null;
			fieldSetFlags()[3] = false;
			return this;
		}

		@Override
		public FeatureDefinition build() {
			try {
				FeatureDefinition record = new FeatureDefinition();
				record.FeatureTypeName = fieldSetFlags()[0] ? this.FeatureTypeName : (java.lang.String) defaultValue(fields()[0]);
				record.AttributeNames = fieldSetFlags()[1] ? this.AttributeNames : (java.util.List<java.lang.String>) defaultValue(fields()[1]);
				record.AttributeTypes = fieldSetFlags()[2] ? this.AttributeTypes : (java.util.List<java.lang.String>) defaultValue(fields()[2]);
				record.AttributeDefaultClassifications = fieldSetFlags()[3] ? this.AttributeDefaultClassifications : (java.util.List<java.lang.String>) defaultValue(fields()[3]);
				return record;
			}
			catch (Exception e) {
				throw new org.apache.avro.AvroRuntimeException(
						e);
			}
		}
	}
}
